### ISSUE TITLE
Word missing in achievement riddle

### ISSUE THREAD

**Issue by MysteryBlokHed** [r-pufky/payday2-secret#11]
In the riddle for achievement 23 (Walk Faster), the riddle has a word missing.
"A house full thugs and low lifes..." should say "A house full **_of_** thugs and low lifes"

**Comment by MysteryBlokHed** [comment]
A picture of the riddle on the tablet:
![9](https://user-images.githubusercontent.com/13910387/85932286-ad48f180-b898-11ea-8882-5c2532ea849f.jpg)

**Comment by r-pufky** [comment]
Thanks for letting me know -- this is now fixed.
