### ISSUE TITLE
door not working? (answerd)

### ISSUE THREAD

**Issue by aftrox** [r-pufky/payday2-secret#14]
when i try to do this its all good until i get to the vault door with the riddles
when i get the answer in and push the lever to send the answer it doesnt do anything?
please help

**Comment by r-pufky** [comment]
Few things could be going on here:

1) If the ring goes in and comes back out; then the input you're setting is wrong, and it's returning you to the first riddle.
2) Unsure what the current state of PD2 is with respect to needing multiple players to activate; you may be running into this case.

Double check the outer ring matches; as well as the three inner rings before pulling the level to activate. I recently did this with four players about 2-3 weeks ago without issue.

Will resolve this bug; generally these bugs are for updates or problems with the info itself. If you can confirm that there is something wrong with the info here, please re-open and we can get it fixed.

**Comment by aftrox** [comment]
weird because i was with 4 poeple all with achievements unlocked and i even translated it fully this time when i enterd it the outer ring didnt even move , not going out or not sending a new riddle?

**Comment by r-pufky** [comment]
Do you have a screenshot of the puzzle in the not working state? It would be helpful to see entire wheel with your answer in the middle.
