### ISSUE TITLE
door still not working?

### ISSUE THREAD

**Issue by aftrox** [r-pufky/payday2-secret#15]
weird because i was with 4 poeple all with achievements unlocked and i even translated it fully this time when i enterd it the outer ring didnt even move , not going out or not sending a new riddle?
and even if i restart the mission it still doesnt work.
opening and closing payday and trying again doesnt work?
rebooting my pc and trying again doest work either?

**Comment by r-pufky** [comment]
Closing this bug. I can't help you debug your game.

With the secret, it's likely mods or missing achievements from one of the 4 players:
* Disable all your mods.
* Ensure all players have all pre-requisites unlocked. The best approach to this is to actually do all achievements listed for each player.
* I'm fairly certain the unlocks are tracked in your save profile, so anyone in the group who's just used an unlocker is likely not going to trigger the secret either (uncertain of this, but it is a distinct possibility).
