### ISSUE TITLE
Incorrect achievement listing

### ISSUE THREAD

**Issue by overheersbeest** [r-pufky/payday2-secret#16]
the text that translates to "Surrounded, the four thieves overcame grave danger and escaped the house of massacre."
is incorrectly listed as being the 'Making a Statement' achievement.
Instead it is supposed to be the 'Puts the "S" in Laughterhouse.' achievement.
Somehow we got one of our players in a state where they completed 'Making a Statement' but not 'Puts the "S" in Laughterhouse.', after completing the other 19 achievements, the secret did not become available (painting didn't glow) during the white house heist. completing the 'Puts the "S" in Laughterhouse.' achievement made the painting glow.

**Comment by r-pufky** [comment]
Thanks for the information. Will be making an update shortly.
