### ISSUE TITLE
missing periods at ends of translated sentences.

### ISSUE THREAD

**Issue by overheersbeest** [r-pufky/payday2-secret#17]
The following achievements don't have periods at the end of their translated sentences:
Self Checkout
What’s in the Box?
Out of bounds
The Pacifist

adding those allows for easier searching when translating the last letters of a sentence, instead of the first (because they vary more from sentence to sentence), by searching with Ctrl+F for translated letters ending on a period.

**Comment by r-pufky** [comment]
No worries -- will be updating shortly.
