### ISSUE TITLE
there isnt an achievement riddle that starts with 'The Law Best Efforts Of Flu"

### ISSUE THREAD

**Issue by SusAnalBumParty** [r-pufky/payday2-secret#21]

**Comment by r-pufky** [comment]
Hrmm, I just searched the page for that text and couldn't find it; as well as the achievements in the game. Can you point to exactly which achievement you are talking about (e.g. the number)?

**Comment by SusAnalBumParty** [comment]
i think i have the picture of a untranslated riddle but i cant send it rn

**Comment by r-pufky** [comment]
Any updates? If not, I'll close the request.

You can attach pictures here by dragging into the composition box. It would help to take a screenshot in game, then attach it here to get it figured out.

**Comment by SusAnalBumParty** [comment]
Oh sorry for the long wait. I couldnt attach the image before, but here it
is

сб, 30 июл. 2022 г., 0:02 r-pufky ***@***.***>:

**Comment by r-pufky** [comment]
Please attach the image directly via github issue. The email response you posted did not contain the image :(

**Comment by r-pufky** [comment]
Closed, no response/updates/confirmations.
