### ISSUE TITLE
Incorrect achievement Listing

### ISSUE THREAD

**Issue by LAguiar-Haedes** [r-pufky/payday2-secret#22]
For the 57th Achievement on the list:

`While Stealing A bomb from a train the four thieves did not spill a single drop of blood.
`

The achievement name is incorrect, instead of **Looting in the Dark** it should be **The Pacifist**

**Comment by r-pufky** [comment]
Related to #3.

Have you just recently completed this to confirm accuracy? This was open for discussion before but never confirmed.

**Comment by LAguiar-Haedes** [comment]
I am in the process of finishing the secret but I installed the [highlighter mod](https://modworkshop.net/mod/23858) and it is currently highlighting **The Pacifist**

I will grind the rest of my achievements while avoiding **Looting in the Dark** and confirm asap.

**Comment by r-pufky** [comment]
Thanks!

**Comment by LAguiar-Haedes** [comment]
Hey! I just finished grinding as I just confirmed that the achievement needed it is not **Looting in the Dark**, as you can see I do not have it unlocked:
![20231125121312_1](https://github.com/r-pufky/payday2-secret/assets/127200007/82b2faa9-18f9-4fc7-bfc0-344d30def24c)

But the painting in the PEOC is glowing
![20231125115848_1](https://github.com/r-pufky/payday2-secret/assets/127200007/6c5a5c4d-ed7d-4900-9207-08f6ab1978e6)
 
And after interacting with it I am allowed to put down the C4
![20231125115916_1](https://github.com/r-pufky/payday2-secret/assets/127200007/acc06c1e-174f-40ee-b0bc-2eedfc907c3d)

With this I can confirm that the correct achievement is **The Pacifist**

**Comment by r-pufky** [comment]
Awesome, thank you will update today!
