### ISSUE TITLE
Correction of Riddle: APATE

### ISSUE THREAD

**Issue by Greedforce** [r-pufky/payday2-secret#23]
The Riddle with APATE as answer reads on the page as:
"I can be trusted to guard the great wealth of the land but do not trust my WORDS"
but in-game it's:
"I am trusted to guard the great wealth of the land but do not trust my WORDS"

Helped a friend with the secret and was scratching my head for a bit when the search on the page didn't work.

**Comment by r-pufky** [comment]
Updated, thanks!
