### ISSUE TITLE
Achievement not yet listed with the 56 others

### ISSUE THREAD

**Issue by Paremo** [r-pufky/payday2-secret#3]
Translated Riddle Text: While Stealing A bomb from a train the four thieves did not spill a single drop of blood
Likely Achievement: Oppressor
Image (not yet mirrored): ![ach 17 _crop](https://user-images.githubusercontent.com/15044558/48207573-37191380-e371-11e8-8ff5-0612fa5ab4c9.jpg)

**Comment by r-pufky** [comment]
It sounds like two possibilities:

Looting in the Dark -- murky station stealth w. no civilian kills. Also main objective is to recover a bomb.

or

Oppressor -- Finish the Bomb: Forest heist without letting any civilian flee or die, having at least five civilians in the heist, while escaping with the boat.

Do you have both unlocked already? Would you be able to test?

I will add to the list of achievements, thanks for the help!

**Comment by r-pufky** [comment]
I should say I think looting in the dark is more likely as you can full stealth without killing anyone, which fits better than the forest for the "single drop" line

**Comment by Paremo** [comment]
Yeah, that does make more sense, especially since it's in line with the riddles for I Will pass Through Walls and Pacifish which use the same phrase.
I do have Looting In the Dark and not Oppressor. I'm lacking Overdrill, but I'll check it out and get back to you once I collect that.

**Comment by r-pufky** [comment]
Awesome, thank you!  I've already added it and will clarify once I hear back.

**Comment by r-pufky** [comment]
Just wondering if you had any updates on this. If not, I'll resolve issue and set to "Looting in the Dark" until otherwise determined to be incorrect.

**Comment by Paremo** [comment]
I did Overdrill, but haven't gotten around to trying the actual secret - and frankly, I probably won't in the near future.
So you should probably go ahead and do that.

**Comment by r-pufky** [comment]
SGTM.
